#!/usr/bin/env bash
# Install `dsh` and write the headless profile the DSH review and triage jobs run under.
#
# A GitHub-hosted runner starts empty, so this runs once per CI job rather than
# once per machine. It is idempotent and also serves a durable workstation
# through scripts/setup-review-profile.sh.
#
# The profile patch is a top-level YAML array of id-targeted overrides applied
# over the composed bundle layers. A patch replaces the targeted row's whole
# `config`, so every row below restates the complete configuration it wants,
# not just the changed field.
set -euo pipefail

DSH_PACKAGE="${DSH_PACKAGE:-@deepseek-ai/dsh}"
DSH_PACKAGE_VERSION="${DSH_PACKAGE_VERSION:-0.1.0-rc.6}"
DSH_HOME="${DSH_HOME:-$HOME/.dsh}"
DSH_PROFILE="${DSH_PROFILE:-headless}"

# Provider-agnostic: any pi-ai catalog route or hand-declared OpenAI-compatible /
# Anthropic-Messages endpoint works, not only Ollama Cloud. Every value below is a
# knob, not a hardcoded target; the defaults happen to be this fork's current
# provider. DSH_PROVIDER_KEY_ENV names the environment variable dsh resolves the
# credential *reference* from at request time — it is deliberately not named after
# any one provider, so switching providers never means renaming a GitHub secret.
DSH_PROVIDER_ID="${DSH_PROVIDER_ID:-ollama}"
DSH_PROVIDER_API="${DSH_PROVIDER_API:-openai-completions}"
DSH_PROVIDER_BASE_URL="${DSH_PROVIDER_BASE_URL:-https://ollama.com/v1}"
DSH_PROVIDER_KEY_ENV="${DSH_PROVIDER_KEY_ENV:-DSH_PROVIDER_API_KEY}"
DSH_MODEL_ID="${DSH_MODEL_ID:-deepseek-v4-pro:0813}"
DSH_MODEL_CONTEXT_WINDOW="${DSH_MODEL_CONTEXT_WINDOW:-131072}"
DSH_MODEL_MAX_TOKENS="${DSH_MODEL_MAX_TOKENS:-8192}"

fail() {
  echo "bootstrap-dsh-profile: $1" >&2
  exit 1
}

if [ -z "${!DSH_PROVIDER_KEY_ENV:-}" ]; then
  fail "\$$DSH_PROVIDER_KEY_ENV is empty; set it as an Actions secret (or export it locally) before bootstrapping."
fi

# The key never enters the profile: the patch stores the *reference* below and
# dsh resolves it from the environment per request.
if ! command -v dsh >/dev/null 2>&1; then
  echo "bootstrap-dsh-profile: installing ${DSH_PACKAGE}@${DSH_PACKAGE_VERSION}"
  npm install -g "${DSH_PACKAGE}@${DSH_PACKAGE_VERSION}"
fi
command -v dsh >/dev/null 2>&1 || fail 'dsh is still not on PATH after npm install -g.'

profile_dir="$DSH_HOME/profiles/$DSH_PROFILE"
patch_file="$profile_dir/cordis.patch.yml"

# `headless` and `web` are auto-initializing profile templates: composing the
# config is what creates the directory. The composition can legitimately fail
# here (no patch is written yet), so the failure is only fatal if it left no
# profile behind.
init_log="$(mktemp)"
trap 'rm -f "$init_log"' EXIT
dsh --profile "$DSH_PROFILE" --dump-config >/dev/null 2>"$init_log" || true
if [ ! -d "$profile_dir" ]; then
  echo "bootstrap-dsh-profile: profile init output:" >&2
  cat "$init_log" >&2
  fail "dsh did not create $profile_dir; '$DSH_PROFILE' may not be an auto-initializing profile template on this dsh version."
fi

cat > "$patch_file" <<PATCH_EOF
# Generated by scripts/bootstrap-dsh-profile.sh — edit that script, not this file.
#
# Read-only analysis profile: dsh reads the checkout and answers, and never
# writes a file or waits for an approval prompt that no one is there to answer.

# Composed sandbox and approval defaults must agree with the preset table below,
# so all three rows move together. Patching only \`permission\` leaves the
# environment-derived defaults in place and fails the load with
# "composed sandbox and approval defaults match no preset".
- id: sandbox-policy
  config:
    mode: read-only
    workspaceRoot: !!js process.cwd()

- id: approval
  config:
    policy: never

- id: permission
  config:
    defaultPreset: read-only
    presets:
      read-only:
        sandbox: read-only
        approval: never
      workspace-write:
        sandbox: workspace-write
        approval: ask
      danger-full-access:
        sandbox: danger-full-access
        approval: never

# The generic multi-provider adapter mounts dormant until a route is declared.
# \`apiKeyEnv\` is a credential reference resolved per request; no secret is
# stored here.
- id: llm-pi-ai
  config:
    providers:
      $DSH_PROVIDER_ID:
        apiKeyEnv: $DSH_PROVIDER_KEY_ENV
        api: $DSH_PROVIDER_API
        baseURL: $DSH_PROVIDER_BASE_URL
        models:
          - id: $DSH_MODEL_ID
            contextWindow: $DSH_MODEL_CONTEXT_WINDOW
            maxTokens: $DSH_MODEL_MAX_TOKENS

- id: agent-default-model
  config:
    provider: $DSH_PROVIDER_ID
    model: $DSH_MODEL_ID

- id: system-prompt
  config:
    persona: >-
      You are a meticulous senior software engineer reviewing someone else's work.
      Judge only the material you are given. State findings as concrete, actionable
      claims with file and symbol names, and say plainly when the material is
      insufficient to reach a conclusion rather than guessing.
PATCH_EOF

# Misconfiguration fails here, in bootstrap, rather than inside a review job.
if ! dsh --profile "$DSH_PROFILE" --dump-config >/dev/null; then
  fail "the composed '$DSH_PROFILE' profile does not load; see the dump-config output above and $patch_file."
fi

echo "bootstrap-dsh-profile: ready — profile '$DSH_PROFILE', provider '$DSH_PROVIDER_ID' ($DSH_PROVIDER_API @ $DSH_PROVIDER_BASE_URL), model '$DSH_MODEL_ID'"
